### PR TITLE
Use a submodule for upstream objcryst

### PR DESCRIPTION
**Pull request by vincefn**
This PR aims to use a [git submodule](https://git-scm.com/book/en/v2/Git-Tools-Submodules) to sync `libobjcryst` with the upstream `objcryst`.

This is _much_ simpler than using a different branch to sync the upstream `objcryst` repository, then cleaning up the changes in the upstream branch every time something not in the core objcryst `*.cpp` and `*.h` has changed (.e.g. the graphical components, the Fox application, the objcryst:Fox documentation etc...).

I don't expect there's any drawback, it just requires making a recursive git checkout, e.g. for the submodules branch:

`git clone --branch submodules --recursive https://github.com/diffpy/libobjcryst.git`

It also requires using `-DREAL=double` in the command-line rather than changing the source, but that's trivial - I already pushed [the corresponding change](https://github.com/diffpy/pyobjcryst/commit/d8fe90902f5d042c96c82614d60ff30cae7ea7cb) in pyobjcryst.

@sbillinge @st3107 let me know if this can be an issue in your integration pipelines.

### CODE REVIEW

**Comment by sbillinge** [comment]
@vincefn I don't see any issues for us with this change. It would be nice to hear from @pavoljuhas on this. 

We now have pre-commit.ci running on all our diffpy repos.  We may want to switch this off for the current repo, or put in a very light pre-commit-config.yaml that doesn't do much at all.  @vincefn what is your preference here?

**Comment by vincefn** [comment]
@sbillinge regarding the CI, it is always good to have some CI. I see it's failing here - is that because the configuration file is missing (`.pre-commit-config.yaml`) ? The pre-commit is activated by a repository setting ? Of course for this repo maybe it's not so useful since it's mostly relying on the upstream repo, so yes a lightweight version may be enough.

I'll wait anotehr day to see if @pavoljuhas has a comment - I think the original approach was because using git submodules was only introduced in 2007, so it was probably not a very usual approach then (or well integrated in pipelines). Not having to cleanup every change outside the non-GUI ObjCryst classes will be much easier.

**Comment by sbillinge** [comment]
@vincefn I will make A PR which should allow the Pre-K omit to pass.  We are now using this to ensure linting standards on all our repos.

**Comment by pavoljuhas** [comment]
LGTM as far as I can tell.  IIRC, the reason for having a derived branch was to exclude GUI-related sources from libObjCryst and to have an option for small downstream patches.  If submodule works as well and is easier to maintain, it is the way to go.

**Pull request merged**
